#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistema
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_sistema")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_categoria(tb_categoria instance);
    partial void Updatetb_categoria(tb_categoria instance);
    partial void Deletetb_categoria(tb_categoria instance);
    partial void Inserttb_produto(tb_produto instance);
    partial void Updatetb_produto(tb_produto instance);
    partial void Deletetb_produto(tb_produto instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::sistema.Properties.Settings.Default.db_sistemaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_categoria> tb_categorias
		{
			get
			{
				return this.GetTable<tb_categoria>();
			}
		}
		
		public System.Data.Linq.Table<tb_produto> tb_produtos
		{
			get
			{
				return this.GetTable<tb_produto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_categoria")]
	public partial class tb_categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_categoria;
		
		private string _desc_categoria;
		
		private EntityRef<tb_categoria> _tb_categoria2;
		
		private EntitySet<tb_produto> _tb_produtos;
		
		private EntityRef<tb_categoria> _tb_categoria1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categoriaChanging(int value);
    partial void Onid_categoriaChanged();
    partial void Ondesc_categoriaChanging(string value);
    partial void Ondesc_categoriaChanged();
    #endregion
		
		public tb_categoria()
		{
			this._tb_categoria2 = default(EntityRef<tb_categoria>);
			this._tb_produtos = new EntitySet<tb_produto>(new Action<tb_produto>(this.attach_tb_produtos), new Action<tb_produto>(this.detach_tb_produtos));
			this._tb_categoria1 = default(EntityRef<tb_categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					if (this._tb_categoria1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc_categoria", DbType="NVarChar(50)")]
		public string desc_categoria
		{
			get
			{
				return this._desc_categoria;
			}
			set
			{
				if ((this._desc_categoria != value))
				{
					this.Ondesc_categoriaChanging(value);
					this.SendPropertyChanging();
					this._desc_categoria = value;
					this.SendPropertyChanged("desc_categoria");
					this.Ondesc_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_categoria_tb_categoria", Storage="_tb_categoria2", ThisKey="id_categoria", OtherKey="id_categoria", IsUnique=true, IsForeignKey=false)]
		public tb_categoria tb_categoria2
		{
			get
			{
				return this._tb_categoria2.Entity;
			}
			set
			{
				tb_categoria previousValue = this._tb_categoria2.Entity;
				if (((previousValue != value) 
							|| (this._tb_categoria2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_categoria2.Entity = null;
						previousValue.tb_categoria1 = null;
					}
					this._tb_categoria2.Entity = value;
					if ((value != null))
					{
						value.tb_categoria1 = this;
					}
					this.SendPropertyChanged("tb_categoria2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_categoria_tb_produto", Storage="_tb_produtos", ThisKey="id_categoria", OtherKey="id_categoria")]
		public EntitySet<tb_produto> tb_produtos
		{
			get
			{
				return this._tb_produtos;
			}
			set
			{
				this._tb_produtos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_categoria_tb_categoria", Storage="_tb_categoria1", ThisKey="id_categoria", OtherKey="id_categoria", IsForeignKey=true)]
		public tb_categoria tb_categoria1
		{
			get
			{
				return this._tb_categoria1.Entity;
			}
			set
			{
				tb_categoria previousValue = this._tb_categoria1.Entity;
				if (((previousValue != value) 
							|| (this._tb_categoria1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_categoria1.Entity = null;
						previousValue.tb_categoria2 = null;
					}
					this._tb_categoria1.Entity = value;
					if ((value != null))
					{
						value.tb_categoria2 = this;
						this._id_categoria = value.id_categoria;
					}
					else
					{
						this._id_categoria = default(int);
					}
					this.SendPropertyChanged("tb_categoria1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_produtos(tb_produto entity)
		{
			this.SendPropertyChanging();
			entity.tb_categoria = this;
		}
		
		private void detach_tb_produtos(tb_produto entity)
		{
			this.SendPropertyChanging();
			entity.tb_categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_produto")]
	public partial class tb_produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_produto;
		
		private string _desc_produto;
		
		private System.Nullable<decimal> _valor;
		
		private System.Nullable<int> _id_categoria;
		
		private EntityRef<tb_categoria> _tb_categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_produtoChanging(int value);
    partial void Onid_produtoChanged();
    partial void Ondesc_produtoChanging(string value);
    partial void Ondesc_produtoChanged();
    partial void OnvalorChanging(System.Nullable<decimal> value);
    partial void OnvalorChanged();
    partial void Onid_categoriaChanging(System.Nullable<int> value);
    partial void Onid_categoriaChanged();
    #endregion
		
		public tb_produto()
		{
			this._tb_categoria = default(EntityRef<tb_categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_produto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_produto
		{
			get
			{
				return this._id_produto;
			}
			set
			{
				if ((this._id_produto != value))
				{
					this.Onid_produtoChanging(value);
					this.SendPropertyChanging();
					this._id_produto = value;
					this.SendPropertyChanged("id_produto");
					this.Onid_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc_produto", DbType="NVarChar(50)")]
		public string desc_produto
		{
			get
			{
				return this._desc_produto;
			}
			set
			{
				if ((this._desc_produto != value))
				{
					this.Ondesc_produtoChanging(value);
					this.SendPropertyChanging();
					this._desc_produto = value;
					this.SendPropertyChanged("desc_produto");
					this.Ondesc_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", DbType="Int")]
		public System.Nullable<int> id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					if (this._tb_categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_categoria_tb_produto", Storage="_tb_categoria", ThisKey="id_categoria", OtherKey="id_categoria", IsForeignKey=true)]
		public tb_categoria tb_categoria
		{
			get
			{
				return this._tb_categoria.Entity;
			}
			set
			{
				tb_categoria previousValue = this._tb_categoria.Entity;
				if (((previousValue != value) 
							|| (this._tb_categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_categoria.Entity = null;
						previousValue.tb_produtos.Remove(this);
					}
					this._tb_categoria.Entity = value;
					if ((value != null))
					{
						value.tb_produtos.Add(this);
						this._id_categoria = value.id_categoria;
					}
					else
					{
						this._id_categoria = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
